# swagger
knife4j:
  enable: true
  production: true

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manager
    username: root
    password: root

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
